// Chapter titles — a flat, editable list. Add as many as you like; nothing
// below is logic, and nothing else needs changing when you do.
//
// Each chapter of a run draws one at random and keeps it for the rest of that
// run, so a reload never renames a chapter under you. Titles aren't repeated
// within a run until the list runs out, so a longer list means a stranger book.

export const CHAPTER_TITLES = [
  'The coming of the insects',
  'Egads!',
  'Horrors that the Human Mind Cannot Comprehend',
  'Lady Pemberley comes to tea',
  'The funeral',
  'The devil comes to Egg City',
  'Nine weeks at sea',
  'Shipwrecked!',
  '"It is fortunate for us that ghosts do not exist"',
  'Shocking plot twist!',
  'A confusing piece of dirt',
  'Dramatic Betrayal!',
  'Temptation',
  'Unending sexual tension',
  'Mission: Success',
  'Galaxo is Drunk Again',
  'A Superposition of Past and Future',
  'Mandibles',
  '"Galaxo, Stop Killing Civilians!"',
  'Nanobots Save the Day!',
  'A squirrel of immense power',
  'The Diary of Lady Pemberley',
  'Cara braves a climate-ravaged hellscape',
  'The protagonist dies',
  'Two characters have a conversation',
  'Suddenly, zombies!',
  'Betrayal!',
  'Not very much is happening',
  'The ghost was actually childhood trauma',
  'Lots of kissing',
  'Surprise Villain!',
  'Whatever pain you feel must be borne of something',
  'The Reason Everybody Hates Theo',
  'Critical exegesis',
  'The redemption of a bad man',
  'Chainsaw Massacre',
  'The Wedding',
  'A pastoral interlude',
  'Inevitable Knife-Crimes',
  'Those chums of yore',
  'Cliffside confessions',
  'The Problem with Uncle Howard',
  'A Monologue about Capitalism',
  'Half-man, half-spider',
  'Ethical implications',
  'Explosions!',
  'Flashback!',
  'Allegory for Mental Health Struggles',
  'The Tortoise, Emerging',
  'Who left the footprints in the garden?',
  '“I can’t believe she was cheating on him!”',
  'A dreadful surmise',
  'The Academic Review Process Begins',
  'The detective re-appears',
  'Another flashback!',
  'Another attempt to talk to the bird',
  '“Pull that lever, baby!”',
  'Tender murmurings',
  'The Crabcosan prophecy',
  'It was all just a metaphor!',
  'Padding the word count',
  'Here comes a tragedy!',
  'Approaching light-speed',
  'The Ghost Was Actually Dinah’s Undiagnosed Bipolar',
  'The Oafish Servant',
  'The Servile Oaf',
  'Onwards!',
  'The watermelon cult',
  'There’s a Story Going On Here If I Can Only Figure Out What It Is',
  '35℃, 92% Humidity',
  'Luc, Suddenly Enormous',
  'Richard Sernandez',
  'Becoming a worm',
  'The Distant Cloud of Inexpressible Sorrow',
  'Self-Destructive Behaviour',
  'The girl on the monorail',
  'An Allegory for WW2',
  'Mist, possibly containing werewolves, rolls into town',
  'Very Sexy Vampires',
  'Will the dog survive?',
  'We never did understand time',
  'Surprise Identical Twin',
  'It’s not over yet!',
  'Incoherent screaming',
  'Clowns in the night',
  'The killer is revealed!',
  'The Greyound Waltz',
  '"What the fuck was that?"',
  'Bruce was dead all along?!',
  'Surprise sex!',
  'Boarding the spaceship',
  'Half-spider, half-slug',
  '“Who among you is more beautiful than I?”',
  'A minor character is eaten by a shark',
  'Smouldering Side-long Glances',
  'The wedding',
  'Uncle Howard catches a wasp in the garden shed',
  'Fish-monger Larry',
  'Some light cannibalism',
  'The unfortunate appearance of Willowby the Chain-Monster',
  'Blood and vengeance',
  'To kill a sparrow-bird',
  'Word and peas',
  'Poisoned sugar-bowl',
  'The bloodening',
  'The Really Really Handsome Tax-Accountant',
  'Love and Guns',
  'Love in the air, death at the fair',
  'The imposter',
  '“Actually, I’m her clone”',
  'Duel to the death',
  'Star-bound voyagers',
  'The naked ladies on the bus',
  '"Objection, Your Honour!"',
  'Wedding massacre',
  'The Part Where Things Get Meta',
  'Chain and Pain',
  'Fourteen people will imminently die',
  'The Paris sewerage system',
  'Revenge',
  'The Can of Worms, Opened',
  'Enter the Genetically Modified Gorillas',
  'The Large Sad Thing is Back',
  'The Antwerp Incident',
  'An ethical violation',
  'Big Ears',
  'Pistols and fisticuffs',
  'Watching the paint dry',
  'Memories',
  'Exposition!',
  'Man the harpoons!',
  'The Queen’s Secret Lover, Bob',
  'Who shot the postman?',
  'Greetings, Antelope',
  'A hushed conversation in the ruined colloseum',
  'The snail makes a surprising choice',
  'Meeting the Contessa',
  'Dracula’s Descendants',
  'A brief moment of poignancy',
  'Everything up to here was actually a dream',
  'The mysterious dentist',
  'Time Loop!',
  'Treachery in the Laundry Room',
  'A passing lance impales Sir Kevan',
  'Four characters that are all called Bob',
  '“I have to see it!” he shrieks. “I have to see the thing!”',
  'The Lady of Situations',
  'Unedifying scenes in the bakery',
  'Melanie rises from the mud, resplendent',
  'The monolith’s shape and proportions suggest it is the work of intelligent beings',
  'Suddenly, extraterrestrials!',
  'The portal to the moon',
  'A matter of justice',
  'The Interrogation',
  'Courtroom shenanigans',
  'Doctor Policeman, M.D.',
  '“You ain’t no lawyer, you a dead man.”',
  'Everyone is a suspect',
  '“A dog cannot testify in court.”',
  'A surprise deposition',
  'Uncle Howard enters Witness Protection',
  'The unstoppable human lawnmower',
  'Paperwork',
  '“What about your secret homosexual lover, who thinks you’re in Paris?”',
  'Tumbles the Crime-Fighting Cat',
  '“At least one of us is a Russian spy”',
  'The Syndicate',
  'Hooves on cobblestones',
  '“Who is this woman, and why is her room full of knickers?”',
  'Good seafaring folk',
  'Touchdown!',
  'Let’s Get Down to Love',
  'Viking Magic',
  'The World, Aflame',
  'The chickens get their revenge',
  'Lord Hurburton’s Dainty Daughter',
  'The Mermaid Of The Lower Reservoir',
  'Charles Augustus Milverton',
  'The Sun, The Sun!',
  'The stranger’s treasure map',
  'Foreshadowing!',
  'Four bears',
  'Uncle Howard is subjected to a smear campaign',
  'Origin Story!',
  'A digression on Uncle Howard’s Enormous Moustache',
  '“What are we, if not the world’s hallucination?”',
  'Spandex',
  'Galaxo the Underwhelming',
  '"Oh no! There are five people tied to that track!"',
  'Galaxo Fails to Save Anybody',
  '“I suppose you’re wondering why Galaxo is hiding out in your barn.”',
  'Sad sexy alcoholism',
  "Uncle Howard's Right-Hand Man",
  '“No! Don’t probe me there!”',
  'A hot wilted morning in December',
  'Existential angst!',
  'The plot gets really really thick',
  'Conspiracy!',
  'A visit to the circus',
  'Holy shit!',
  'This chapter actually kinda does make sense in a postmodern kind of way',
  'A knock on the door',
  'Scary, colourless worms',
  'Suddenly: bees!',
  'A tender kiss',
  'Magic!',
  'Things get steamy',
  'Uncle Howard serves as Comic Relief',
  'The Dirt Man Cometh',
  'Cara finds out she is a wizard',
  'Cara fights her internal demons',
  'Cara fights seven or eight ninjas',
  'Cara sips a glass of water',
  'Cara falls in love, briefly',
  'Cara writes a poem',
  'Cara’s reflection looks less and less like her',
  'Cara eats a sandwich',
  'Cara has a long shift at the convenience store',
  'Cara escapes her captors',
  'Cara brews some tea',
  'Cara’s ex-boyfriend buys a motorcycle',
  'Cara sabotages a seance',
  'The party splits up',
  'The character who appeared to have died is actually alive',
  'Half-chicken, half-horse',
  '“The only ones left here are us.”',
  'Everybody wants the doom-hat',
  'Cara’s ex-boyfriend saves the day!',
  'The Heir Apparent',
  'An ancient pact',
  'Reclaiming the throne',
  'The quiet dignity of the garbage man',
  'Mild dehydration',
  'Nine years later',
  '"Just cudgel him already!"',
  '"Uncle Howard, let her out of your basement!"',
  'Belinda has a job to do',
  'The hiking accident',
  'Monsters on the mezzanine',
  'War Mouse',
  'A faux pas at the dinner party',
  'A serious case of The Sillies',
  'A singularly unfortunate event',
  'A character who is a novelist works on his own novel',
  'The supremely sexy robot',
  'The Robot Uprising',
  'Plague!',
  'One last shift at the police station before retirement',
  'Get inside the Danger Cube',
  '''ger
];
