// Chapter titles — a flat, editable list. Add as many as you like; nothing
// below is logic, and nothing else needs changing when you do.
//
// Each chapter of a run draws one at random and keeps it for the rest of that
// run, so a reload never renames a chapter under you. Titles aren't repeated
// within a run until the list runs out, so a longer list means a stranger book.

export const CHAPTER_TITLES = [
  'The coming of the insects',
  'Egads!',
  'A shocking plot twist',
  'The protagonist dies',
  'Two characters have a conversation',
  'Suddenly, zombies!',
  'Betrayal!',
  'Not very much is happening',
  'The ghost was actually childhood trauma',
  'Lots of kissing',
  'Surprise Villain!',
  'Whatever pain you feel must be borne of something',
  'The Reason Everybody Hates Theo',
  'Critical exegesis',
  'The redemption of a bad man',
  'Those chums of yore',
  'Half-man, half-spider',
  'Ethical implications',
  'Explosions!',
  'Flashback!',
  'An Allegory for Mental Health Struggles',
  'The Tortoise, Emerging',
  'Who left the footprints in the garden?',
  '“I can’t believe she was cheating on him!”',
  'A dreadful surmise',
  'The Academic Review Process Begins',
  'The detective re-appears',
  'Another flashback!',
  'Another attempt to talk to the bird',
  '“Pull that lever, baby”',
  'Tender murmurings',
  'The Crabcosan prophecy',
  'It was all just a metaphor!',
  'Padding the word count',
  'Here comes a tragedy!',
  'Approaching light-speed',
  'The Ghost Was Actually Dinah’s Undiagnosed Bipolar',
  'The Oafish Servant',
  'The Servile Oaf',
  'Onwards!',
  'The watermelon cult',
  'There’s a Story Going On Here If I Can Only Figure Out What It Is',
  '35℃, 92% Humidity',
  'Luc, Suddenly Enormous',
  'Richard Sernandez',
  'Becoming a worm',
  'The Distant Cloud of Inexpressible Sorrow',
  'Another Self-Destructive Behaviour',
  'The girl on the monorail',
  'An Allegory for WW2',
  'Mist, possibly containing werewolves, rolls into town',
  'A Very Sexy Vampire',
  'Will the dog survive?',
  'We never did understand time',
  'Surprise Identical Twin',
  'It’s not over yet!',
  'Incoherent screaming',
  'Clowns in the night',
  'The killer is revealed!',
  'Bruce was dead all along?',
  'Surprise sex!',
  'Boarding the spaceship',
  'Half-spider, half-slug',
  '“Who among you is more beautiful than I?”',
  'A minor character is eaten by a shark',
  'Smouldering Side-long Glances',
  'The wedding',
  'Uncle Howard catches a wasp in the garden shed',
  'Fish-monger Larry',
  'Some light cannibalism',
  'The unfortunate appearance of Willowby the Chain-Monster',
  'Blood and vengeance',
  'To kill a sparrow-bird',
  'Word and peas',
  'Poisoned sugar-bowl',
  'The bloodening',
  'The Really Really Handsome Tax-Accountant',
  'Love and Guns',
  'Love in the air, death at the fair',
  'The imposter',
  '“Actually, I’m her clone”',
  'Duel to the death',
  'Star-bound voyagers',
  'The Part Where Things Get Meta',
  'Chain and Pain',
  'Fourteen people will imminently die',
  'The Paris sewerage system',
  'Revenge',
  'The Can of Worms, Opened',
  'Enter the Genetically Modified Gorilla',
  'The Large Sad Thing is Back',
  'The Antwerp Incident',
  'An ethical violation',
  'Big Ears',
  'Watching the paint dry',
  'Memories',
  'Exposition!',
  'Man the harpoons!',
  'The Queen’s Secret Lover, Bob',
  'Who shot the postman?',
  'Greetings, Antelope',
  'A hushed conversation in the ruined colloseum',
  'The snail makes a surprising choice',
  'Meeting the Contessa',
  'Dracula’s Descendants',
  'A brief moment of poignancy',
  'Everything up to here was actually a dream',
  'The mysterious dentist',
  'Time Loop!',
  'Treachery in the Laundry Room',
  'A passing lance impales Sir Kevan',
  'Four characters that are all called Bob',
  '“I have to see it!” he shrieks. “I have to see the thing!”',
  'The Lady of Situations',
  'Unedifying scenes in the bakery',
  'Melanie rises from the mud, resplendent',
  'The monolith’s shape and proportions suggest it is the work of intelligent beings',
  'Suddenly, extraterrestrials!',
  'The portal to the moon',
  'A matter of justice',
  'Courtroom shenanigans',
  'Doctor Policeman, M.D.',
  '“You ain’t no lawyer, you a dead man.”',
  'Everyone is a suspect',
  '“A dog cannot testify in court.”',
  'A surprise deposition',
  'Uncle Howard enters Witness Protection',
  'The frightening, unstoppable human lawnmower',
  'Paperwork',
  '“What about your secret homosexual lover, who thinks you’re in Paris?”',
  'Tumbles the Crime-Fighting Cat',
  '“At least one of us is a Russian spy”',
  'The Syndicate',
  'Hooves on the cobblestones',
  '“Who is this woman, and why is her room full of knickers?”',
  'Good seafaring folk',
  'Touchdown!',
  'Let’s Get Down to Love',
  'Viking Magic',
  'The World, Aflame',
  'The chickens get their revenge',
  'Lord Hurburton’s Dainty Daughter',
  'The Mermaid Of The Lower Reservoir',
  'Charles Augustus Milverton and Bob',
  'The Sun, The Sun!',
  'The stranger’s treasure map',
  'Foreshadowing!',
  'Four bears',
  'Uncle Howard is subjected to a smear campaign',
  'Origin Story!',
  '“What are we, if not a hallucination?”',
  'Spandex',
  'Galaxo the Underwhelming',
  '“I suppose you’re wondering why Galaxo is hiding out in your barn.”',
  'Sad sexy alcoholism',
  'Bob’s Right-Hand Man',
  '“No! Don’t probe me there!”',
  'A hot wilted morning in December',
  'Existential angst!',
  'The plot gets really really thick',
  'Conspiracy!',
  'A visit to the circus',
  'Holy shit!',
  'The plot actually kind of does make sense in a postmodern kind of way',
  'A knock on the door',
  'Scary, colourless worms',
  'Magic!',
  'Things get steamy',
  'The Dirt Man Cometh',
  'Cara fights her internal demons',
  'Cara fights seven or eight ninjas',
  'Cara falls in love, briefly',
  'Cara writes a poem',
  'Cara’s reflection looks less and less like her',
  'Cara eats a sandwich',
  'Cara has a long shift at the convenience store',
  'Cara escapes her captors',
  'Cara’s ex-boyfriend buys a motorcycle',
  'Cara sabotages a seance',
  'The party splits up',
  'The character who appeared to have died is actually alive',
  'Half-chicken, half-horse',
  '“The only ones left here are us.”',
  'Everybody wants the doom-hat',
  'Cara’s ex-boyfriend saves the day!',
  'The Heir Apparent',
  'An ancient pact',
];
